import React, { useState, useRef, useEffect } from 'react';

type OptimizedImageProps = React.ImgHTMLAttributes<HTMLImageElement> & {
  src: string;
  alt?: string;
  className?: string;
  /** Base64 LQIP data-URI for blur-up placeholder */
  lqip?: string;
};

/**
 * Swap the file extension, preserving query strings.
 * For lossless optimized variants we use the `.lossless.webp` / `.lossless.avif` convention.
 */
function swapToLossless(url: string, newExt: 'webp' | 'avif'): string {
  const [base, query] = url.split('?');
  const withoutExt = base.replace(/\.(png|jpg|jpeg)$/i, '');
  const path = `${withoutExt}.lossless.${newExt}`;
  return query ? `${path}?${query}` : path;
}

function swapExt(url: string, newExt: string): string {
  const [base, query] = url.split('?');
  const withoutExt = base.replace(/\.(avif|webp|jpeg|jpg|png)$/i, '');
  const ext = newExt.startsWith('.') ? newExt : `.${newExt}`;
  const path = withoutExt + ext;
  return query ? `${path}?${query}` : path;
}

const OptimizedImage: React.FC<OptimizedImageProps> = ({ src, alt, className, lqip, style, ...rest }) => {
  const baseSrc = src.split('?')[0];
  const hasImageExt = /\.(jpeg|jpg|png)$/i.test(baseSrc);
  const isAlreadyModern = /\.(avif|webp|gif|svg)$/i.test(baseSrc);
  const loading = (rest as any).loading ?? 'lazy';
  const decoding = (rest as any).decoding ?? 'async';

  const isExternal = src.startsWith('http://') || src.startsWith('https://');
  const isLocal = src.startsWith('/') || src.startsWith('./');

  // For images that are already in modern formats or non-image files, render plain img
  if (isAlreadyModern || (!hasImageExt && !isExternal)) {
    return <img src={src} alt={alt} className={className} loading={loading} decoding={decoding} style={style} {...rest} />;
  }

  // --- Blur-up LQIP state ---
  const [loaded, setLoaded] = useState(false);
  const imgRef = useRef<HTMLImageElement>(null);

  // Check if already loaded (cached) on mount
  useEffect(() => {
    if (imgRef.current?.complete && imgRef.current.naturalWidth > 0) {
      setLoaded(true);
    }
  }, [src]);

  // Build optimized source paths
  let avifSrc: string;
  let webpSrc: string;

  if (isLocal && hasImageExt) {
    // Local files: use lossless variants generated by our optimize script
    avifSrc = swapToLossless(src, 'avif');
    webpSrc = swapToLossless(src, 'webp');
  } else if (isExternal && hasImageExt) {
    // External URLs: swap extension directly
    avifSrc = swapExt(src, '.avif');
    webpSrc = swapExt(src, '.webp');
  } else {
    // Fallback: just render img
    return <img src={src} alt={alt} className={className} loading={loading} decoding={decoding} style={style} {...rest} />;
  }

  const pictureElement = (
    <picture>
      <source srcSet={avifSrc} type="image/avif" />
      <source srcSet={webpSrc} type="image/webp" />
      <img
        ref={imgRef}
        src={src}
        alt={alt}
        className={className}
        loading={loading}
        decoding={decoding}
        onLoad={() => setLoaded(true)}
        style={{
          ...style,
          ...(lqip ? { opacity: loaded ? 1 : 0, transition: 'opacity 0.4s ease' } : {}),
        }}
        {...rest}
      />
    </picture>
  );

  // If LQIP provided, wrap with blur-up container
  if (lqip) {
    return (
      <span style={{ position: 'relative', display: 'inline-block', overflow: 'hidden', ...(style?.width ? { width: style.width } : {}) }}>
        {/* LQIP blur placeholder */}
        <img
          src={lqip}
          alt=""
          aria-hidden="true"
          style={{
            position: 'absolute',
            inset: 0,
            width: '100%',
            height: '100%',
            objectFit: 'cover',
            filter: 'blur(20px)',
            transform: 'scale(1.1)',
            opacity: loaded ? 0 : 1,
            transition: 'opacity 0.4s ease',
            pointerEvents: 'none',
          }}
        />
        {pictureElement}
      </span>
    );
  }

  return pictureElement;
};

export default OptimizedImage;
